source 'https://rubygems.org'

gem 'rails', '3.2.12'
gem 'pg'
# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'uglifier', '>= 1.0.3'
end


group :development, :test do
  gem 'rspec-rails'
  gem 'faker'
  gem 'cool_faker'
end

group :test do
  gem 'shoulda-matchers'
  gem 'factory_girl_rails'
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'database_cleaner'
end

gem 'routing_concerns'
gem 'jquery-rails'
gem 'debugger'
gem 'pry'

gem 'bcrypt'

# To use ActiveModel has_secure_password
gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
